# Usa imagem oficial do Node.js
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package.json yarn.lock ./

# Instala as dependências
RUN yarn install

# Copia o restante do código-fonte
COPY . .

# Expõe a porta (ajuste conforme a porta que o gateway usa)
EXPOSE 3002

# Comando para iniciar o serviço
CMD ["yarn", "start:dev"]
